on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Alerts
        uses: actions/checkout@v4

      - name: Deploy Alerts
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Если папка Alerts не существует, клонируем репозиторий, иначе делаем git pull
            if [ ! -d "Alerts" ]; then
              git clone https://${{ secrets.TOKEN }}@github.com/PANiXiDA/Alerts.git Alerts
            else
              cd Alerts && git pull
            fi
            cd Alerts
            # Перезапускаем контейнер ElastAlert
            docker-compose down --remove-orphans
            docker-compose up -d
